[package]
name = "workflow-panic-hook"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1.0.0"
wasm-bindgen = "0.2.79"
[dependencies.web-sys]
version = "0.3.56"
features = [
    'console',
    'Window',
    'Document',
    'Element',
    'HtmlElement',
]
